export const constants = {
    UPDATE_FACTORY_CONTRACT: "UPDATE_FACTORY_CONTRACT",
    UPDATE_TEMPLATE_CONTRACT: "UPDATE_TEMPLATE_CONTRACT",
    UPDATE_METAMASK_ACCOUNT: "UPDATE_METAMASK_ACCOUNT",
    UPDATE_PREVIOUS_CONTRACT: "UPDATE_PREVIOUS_CONTRACT",
    TURN_ON_DANGER_MODE: "TURN_ON_DANGER_MODE",
    TURN_OFF_DANGER_MODE: "TURN_OFF_DANGER_MODE"
};

export default constants;